[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Don't handle room routes - let the main web app handle them
# [[redirects]]
#   from = "/room/*"
#   to = "/room/:splat"
#   status = 200

# Handle API proxy for room server (for development)
[[redirects]]
  from = "/api/rooms/*"
  to = "http://localhost:3002/api/rooms/:splat"
  status = 200
  force = false


